name: backport

on:
  push:
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_BRANCH: backport
    steps:
      - uses: actions/checkout@v2
      - name: extract branch name
        id: extract_branch
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: check exists pull-request
        id: check_pr
        env:
          HEAD_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          exists_pr=$(gh pr list --head $HEAD_BRANCH | awk '{print $1}')
          if [ -z "$exists_pr" ]; then
            echo "::set-output name=exists_pr::false"
          else
            echo "::set-output name=exists_pr::true"
          fi
      - name: create pull-request
        if: ${{ steps.check_pr.outputs.exists_pr == 'false' }}
        env:
          HEAD_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          merge_branch="${HEAD_BRANCH}_merge_$(date '+%Y%m%d%H%M%S')"
          git config --global user.name "Github Actions"
          git switch -c $merge_branch ${{ github.ref }}
          git push origin $merge_branch
          gh pr create --base $BASE_BRANCH -t "[backport] $HEAD_BRANCH to $BASE_BRANCH" -b ""
      - name: merge pull-request
        run: |
          gh pr merge --auto --merge

  notification:
    needs: backport
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/workflow-conclusion-action@v2
    - uses: 8398a7/action-slack@v3
      if: env.WORKFLOW_CONCLUSION != 'skipped'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ env.WORKFLOW_CONCLUSION }}
        fields: repo,commit,ref,workflow,author,message
        author_name: ${{ github.workflow }}
