name: backport

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: create pull-request
        run: |
          gh pr create -B backport -t "main to backport2aaa" -b ""
      - name: merge pull-request
        run: |
          gh pr merge --auto --merge
