name: build

on:
  push:
    branches:
    - "master"

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update image
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.8.1
          command: |
            cd src/cache/deployments/overlays/
            echo "before ---------------"
            kustomize build .
            kustomize edit set image app_image=nginx@foo
            echo "after ---------------"
            kustomize build .
      - name: git commit
        run: |
          git switch -c build-$GITHUB_RUN_ID origin/master
          git commit -am "buiding image"
          hub pull-request -m "test pr" --no-edit
