name: update changelog

on: 
  push:
    branches:
    - 'pre-release'
  # push:
  #   branches-ignore:
  #     - '**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: check pr
      id: pre_release_pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCH: release
        PRERELEASE_BRANCH: pre-release
      run: |
        pr_number=$(gh pr list --base $RELEASE_BRANCH | grep $PRERELEASE_BRANCH | cut -f 1)
        if [ -z $pr_number ]; then
          echo "not found pre-release PR"
          exit 1
        fi

        echo "::set-output name=pr_number::$pr_number"
    # - name: setup-gh
    #   run: |
    #     brew update
    #     brew install gh
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: update description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCH: release
        # PRE_RELEASE_PR_NUMBER: ${{ steps.pre_release_pr.output.pr_number }}
      run: |
        echo "try go get"
        go get github.com/Songmu/ghch/cmd/ghch

        echo "try ghch"
        ghch --from origin/$RELEASE_BRANCH --format markdown > _CHANGELOG

        echo "try gh pr edit"
        gh pr edit $pr_number --body "$(cat _CHANGELOG)"
