name: pullrequest

on:
  push:
    branches:
    - "*"
    - "!master"

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list
          gh pr create --title "test pr" --body "test pr body2"
