name: go-version

on:
  push:

env:
  GO_VERSION: '1.17.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ GO_VERSION }}
