name: manual

on: 
  pull_request:
    types:
    - closed
  workflow_dispatch:
    inputs:
      flag:
        description: "deploy cluster(dev/stg/prd)"
        required: true
        default: "true"

jobs:
  manual-test:
    if: (github.event.pull_request.merged == true && startsWith(github.head_ref, 'multi-test')) || github.event.inputs.flag == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "env: ${{ github.event.inputs }}"
        echo "build_targets: ${{ github.event.inputs }}"
        echo "all: ${{ github.event.inputs }}"
