name: pull_request_close

on: 
  pull_request:
    types:
    - closed

jobs:
  manual-test:
    if: (github.event.pull_request.merged == true && startsWith(github.head_ref, 'multi-test')) || github.event.inputs.flag == 'true'

    runs-on: ubuntu-latest
    steps:
    - name: print
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        result=$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }})
        echo $result
