name: pre_release

on: 
  pull_request:
    types:
    - closed
  workflow_dispatch:
    inputs:
      env:
        description: "deploy cluster(dev/stg/prd)"
        required:  false
      build_targets:
        description: "paths to build.yaml. multiple files are separated by ','"
        required:  false

jobs:
  manual-test:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'multi-test')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "env: ${{ github.event.inputs }}"
        echo "build_targets: ${{ github.event.inputs }}"
        echo "all: ${{ github.event.inputs }}"
