name: manual

on: 
  workflow_dispatch:
    inputs:
      env:
        description: "deploy cluster(dev/stg/prd)"
        required:  false
      build_targets:
        description: "paths to build.yaml. multiple files are separated by ','"
        required:  false

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "env: ${{ github.event.inputs }}"
        echo "build_targets: ${{ github.event.inputs }}"
        echo "all: ${{ github.event.inputs }}"
    - uses: actions/checkout@v2
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: '3.8.1'
    - name: create pull-request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd src/cache/deployments/overlays
        kustomize edit set image app_image=foo@${{ github.sha }}

        git config --global user.name 'bot'
        git config --global user.email 'bot@users.noreply.github.com'
        git switch -c pre_release/${{ github.sha }} origin/master
        git commit -am 'update images'
        git push
        gh pr create --title "[pre-release] ${{ github.sha }}"
