name: notify-failed

on:
  push:
    branches:
      - main

jobs:
  notification:
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/workflow-conclusion-action@v2
    - uses: 8398a7/action-slack@v3
      if: env.WORKFLOW_CONCLUSION != 'skipped'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ env.WORKFLOW_CONCLUSION }}
        fields: repo,commit,ref,workflow,author,message
        author_name: ${{ github.workflow }}
    - uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: 165
        body: |
          Hi @${{ github.actor }} :wave:
          Failed Job ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
