name: Add PR Assignee

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  assign:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Assigne PR author
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
