name: release

on: 
  pull_request:
    types:
    - closed
  push:
    branches:
    - "**"

jobs:
  release:
    # if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'pre-release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'

    - uses: anothrNick/github-tag-action@1.22.0
      id: tag_bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: major
        WITH_V: true
        DRY_RUN: true

    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO111MODULE: on
        RELEASE_BRANCH: release
      run: |
        echo "tags: ${{ steps.tag_bump.outputs.tag }} ${{ steps.tag_bump.outputs.new_tag }}"
        git tag ${{ steps.tag_bump.outputs.new_tag }}
        git push origin ${{ steps.tag_bump.outputs.new_tag }}

        go get github.com/Songmu/ghch/cmd/ghch
        # ghch --next-version=${{ steps.tag_bump.outputs.new_tag }} --format=markdown
        hub pull-request -b $RELEASE_BRANCH -m "[release] ${{ steps.tag_bump.outputs.new_tag }}" -m $(ghch --next-version=${{ steps.tag_bump.outputs.new_tag }} --format=markdown)
