name: release

on: 
  push:
    branches-ignore:
      - '**'
  # push:
  #   branches: [release]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: anothrNick/github-tag-action@1.22.0
      id: tag_bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: major
        WITH_V: true
        RELEASE_BRANCHES: release
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'
    - name: create changelog
      id: changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go get github.com/Songmu/ghch/cmd/ghch
        ghch --next-version ${{ steps.tag_bump.outputs.new_tag }} --format markdown > _CHANGELOG
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_bump.outputs.new_tag }}
        release_name: 'Release ${{ steps.tag_bump.outputs.new_tag }}'
        body_path: ./_CHANGELOG
        draft: false
        prerelease: false
    - name: create release2master PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Github Actions"
        # TODO: automergeオプションが実装されたら乗り換える https://github.com/cli/cli/issues/2619
        hub pull-request -m "[release 2 master] $(date '+%Y%m%d-%H%M%S')" -b main
