name: release

on: 
  pull_request:
    types:
    - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith('pre-release/', github.base_ref)
    runs-on: ubuntu-latest
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
