name: release

on: 
  pull_request:
    types:
    - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "merged pre-release pull-request"
        echo "event: ${{ github.event }}"
        echo "workflow: ${{ github.workflow }}"
