name: release

on: 
  pull_request:
    types:
    - closed

jobs:
  release:
    # if: github.event.pull_request.merged == true && startsWith(github.base_ref, 'pre-release')
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.base_ref }}
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
