name: release

on: 
  pull_request:
    types:
    - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'pre-release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: anothrNick/github-tag-action@1.12.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: major
        WITH_V: true
        DRY_RUN: true
    - run: |
        echo "output: $new_tag $tag"
