name: release

on: 
  pull_request:
    types:
    - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'pre-release')
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v2
      with:
        ref: origin/master

    - name: fetch release
      run: |
        # checkout multiple ranch (Added master)
        # https://github.com/actions/checkout/issues/214
        git fetch --no-tags --depth=1 origin release
        git checkout -b release
        git checkout ${{ github.sha }}

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'

    - uses: anothrNick/github-tag-action@1.22.0
      id: tag_bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: major
        WITH_V: true
        DRY_RUN: true

    - uses: hmarr/debug-action@v1.0.0

    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO111MODULE: on
        RELEASE_BRANCH: release
      run: |
        git --no-pager branch --list

        echo "tags: ${{ steps.tag_bump.outputs.tag }} ${{ steps.tag_bump.outputs.new_tag }}"
        git tag ${{ steps.tag_bump.outputs.new_tag }}
        git push origin ${{ steps.tag_bump.outputs.new_tag }}

        go get github.com/Songmu/ghch/cmd/ghch
        echo -e "[release] ${{ steps.tag_bump.outputs.new_tag }}\n" > _CHANGELOG
        ghch --from $RELEASE_BRANCH --format markdown >> _CHANGELOG
        hub pull-request --base $RELEASE_BRANCH --head master --file _CHANGELOG
