name: release

on: 
  pull_request:
    types:
    - closed

jobs:
  create_release_pr:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'pre-release')
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'

    - uses: anothrNick/github-tag-action@1.22.0
      id: tag_bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: major
        WITH_V: true
        DRY_RUN: true
        RELEASE_BRANCHES: '*'

    - uses: hmarr/debug-action@v1.0.0

    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO111MODULE: on
        RELEASE_BRANCH: release
      run: |
        go get github.com/Songmu/ghch/cmd/ghch
        echo -e "[release] ${{ steps.tag_bump.outputs.new_tag }}\n" > _CHANGELOG
        ghch --from origin/$RELEASE_BRANCH --format markdown >> _CHANGELOG
        hub pull-request --base $RELEASE_BRANCH --head master --file _CHANGELOG

  release_tag:
    if: github.event.pull_request.merged == true && github.head_ref == 'master' && github.base_ref == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: anothrNick/github-tag-action@1.22.0
      id: tag_bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: major
        WITH_V: true
        RELEASE_BRANCHES: release

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.6'

    - name: create changelog
      id: changelog
      env:
        GO111MODULE: on
      run: |
        go get github.com/Songmu/ghch/cmd/ghch
        echo "::set-output name=changelog::$(ghch --latest --format markdown)"

    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_bump.outputs.new_tag }}
        release_name: 'Release ${{ steps.tag_bump.outputs.new_tag }}'
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
