name: sandbox

on:
  push:
  workflow_dispatch:
    inputs:
      vars:
        description: ''
        required: false
        default: 'a,b,c'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        touch $(date '+%s')
        git status
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: |
        git status
