name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      continue-on-error: true
      run: |
        yarn global add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH
        which firebase
    - name: a
      run: |
        which firebase
        echo $GITHUB_PATH
        firebase --version
