name: Test

on: 
  push:
    # branches:
    # - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: setup
      run: |
        user_list=$(cat /etc/passwd)
        user_list="${url_list//$'\n'/\\n}"
        echo $user_list
        echo "::set-output name=user_list::$user_list"
    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const msg = "hello " + ${{ steps.setup.outputs.user_list }}
          github.issues.createComment({
            issue_number: 94,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: msg,
          })
