name: test

on:
  pull_request:
    types:
    - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: print
      run: |
        echo "PR_NUMBER ${{ github.event.pull_request.number }}"
