name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: create pre-release branch
      env:
        PRE_RELEASE_BRANCH: 'pre-release'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git branch -a
        out=$(git branch -a | grep "remotes/origin/$PRE_RELEASE_BRANCH$")
        if [ $? -ne 0 ]; then
          # 既に作成済みであればスキップ
          echo "skip create pre-release branch"
          exit 0
        fi

        git config --global user.name "Github Actions"
        git switch -c $PRE_RELEASE_BRANCH ${{ github.ref }}

        dateVer=$(date '+%Y%m%d-%H%M%S')
        git commit -am "pre-release $dateVer"
        git push origin $PRE_RELEASE_BRANCH
        hub pull-request -m "[pre-release] $(date '+%Y%m%d-%H%M%S')" -b release
