name: test

on:
  push:
    branches:
    - '*'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build_preview
      env:
        WORKING_BRANCH: 'preview/${{ github.run_id }}'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        touch ${{ github.run_id }}

        git add .
        git config --global user.name "Github Actions"
        git switch -c $WORKING_BRANCH ${{ github.ref }}
        git commit -am "[preview] ${{ github.run_id }}"
        git push origin $WORKING_BRANCH

        gh pr create --title "preview ${{ github.run_id }}" --base master --head $WORKING_BRANCH --draft
