name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      continue-on-error: true
      run: |
        yarn global add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH
        which firebase
    - name: a
      run: |
        which firebase
        echo $GITHUB_PATH
        firebase --version
    - name: print
      run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
    - uses: actions/github-script@v3
      env:
        JOB_URL: ${{ $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const msg = `${process.env.JOB_URL}`
          github.issues.createComment({
            issue_number: '112',
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: msg
          })
